### ISSUE TITLE
Blitz no longer launches after 1.14.18 patch

### ISSUE THREAD

**Issue by buttmuncher420** [lulzsun/blitz-app-adblock#56]
There is no error message, it just closes immediately upon opening with this adblocker installed.

**Comment by MortyMcFly420** [comment]
Same here, it tries to launch but just ends poppin into close.

**Comment by zach-v** [comment]
To elaborate more on this issue as it's crashing for many...
here is an example log output from running the patcher on a fresh install of blitz.
`Checking for Blitz...
win32
Extracting app.asar...
Downloading ad & tracking filters...
Patching...
C:\Users\Redacted\AppData\Local\Programs\Blitz\resources/app/src/createWindow.js => Writing to line 276: try {const fs = require('fs');const { FiltersEngine, Request } = require('./adblocker.umd.min.js');const filters =fs.readFileSync(require.resolve('./easylist.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./easyprivacy.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./ublock-ads.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./ublock-privacy.txt'), 'utf-8') + '\n' +fs.readFileSync(require.resolve('./peter-lowe-list.txt'), 'utf-8') + '\ngoogleoptimize.com\n';const engine = FiltersEngine.parse(filters);windowInstance.webContents.session.webRequest.onBeforeRequest({ urls: ['*://*/*'] }, (details, callback) => {const {match} = engine.match(Request.fromRawDetails({ url: details.url }));if (match == true) {log.info('BLOCKED:', details.url);callback({cancel: true});} else {callback({cancel: false});}});} catch (error) {log.error(error);}
C:\Users\Redacted\AppData\Local\Programs\Blitz\resources/app/src/createWindow.js => Writing to line 103: session: true,
Repacking app.asar...
Cleaning up directory...

Patching complete! GLHF :)

Press ENTER to quit...`

Opening blitz will just crash without a warning visible. Checking event viewer we find this:
`Faulting application name: Blitz.exe, version: 1.14.18.625, time stamp: 0x600b6b52
Faulting module name: ntdll.dll, version: 10.0.19041.964, time stamp: 0xb7db0838
Exception code: 0xc0000005
Fault offset: 0x0005f563
Faulting process id: 0xe74
Faulting application start time: 0x01d75d40a5ef7ed2
Faulting application path: C:\Users\Redacted\AppData\Local\Programs\Blitz\Blitz.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: a7f9dcf9-1bcf-4b0a-82f4-aa45c96e6bc3
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by GoldenLumia** [comment]
Confirmed, not working.

**Comment by MauroCastro1705** [comment]
idem

**Comment by majorcyto** [comment]
Can confirm, it is not working.

**Comment by hellabump** [comment]
same its still broken

**Comment by Sarm1X** [comment]
Can confirm its refusing to start up

**Comment by 216049245** [comment]
I had the exact same issue as everyone else.

Solution:

Try running the installer for blitz again, it appears to be working after that and with no ads too!

**Comment by IamKevio** [comment]
I'm having the same issue. So do we know exactly why this is happening? A fix from blitz, or?? Thank you for any input.

**Comment by BroManDudeGuyPhD** [comment]
Same issue here - crashing when running Blitz

**Comment by TMKCRepo** [comment]
Can confirm. Latest release of the Adblock breaks Blitz after installed.

**Comment by Sarm1X** [comment]
Any updates regarding the issue dev? :)

**Comment by lulzsun** [comment]
I believe there is some file signature check, because any type of modification to the app.asar file will cause this crash/close on launch.

Here are the things that I have tested:

1. Extracting app.asar to `/app` and deleting app.asar using 7zip
2. Modify app.asar without extracting and repacking using 7zip
3. Extracting app.asar (making no changes), and repacking using 7zip

All of the above causes a crash on startup, which leads me to believe it is a signature check. I'm not sure if its an electron feature or if it is something that Blitz has done to prevent things like this. I haven't looked into it any deeper then the tests I have done, it is not in my priorities to dive any deeper than this.

However, there are possible ways to go around this issue. One idea that I've thought about trying is to just inject javascript into the electron renderer. [Here's an example](https://github.com/tintinweb/electron-inject) of someone doing this. If anyone wants to test out something like this, I'd like to know the results, as I am currently no longer motivated to fix this on my own time.

**Comment by adamski90** [comment]
I have found a workaround with the following steps:

1. Install Blitz
2. Install Blit App Adblock
3. Navigate to C:\users\YourWindowsUsername\AppData\Local\blit-update *
4. Run installer.exe

Then the application seems to run ok. I am not seeing ads.

*
_With default windows settings the AppData folder may not be visible. If you hit your windows key then type 'folder settings' and press enter -> view panel on top -> tick 'show hidden folders' option - then AppData folders will be visible._

**Comment by Sarm1X** [comment]
> 
> 
> I have found a workaround with the following steps:
> 
>     1. Install Blitz
> 
>     2. Install Blit App Adblock
> 
>     3. Navigate to C:\users\YourWindowsUsername\AppData\Local\blit-update *
> 
>     4. Run installer.exe
> 
> 
> Then the application seems to run ok. I am not seeing ads.
> 
> 
> _With default windows settings the AppData folder may not be visible. If you hit your windows key then type 'folder settings' and press enter -> view panel on top -> tick 'show hidden folders' option - then AppData folders will be visible._

 Did the following steps, but as it seems to patch blitz right back, the application ads are still showing on my end. 
 Not working for me.

**Comment by AEPGANGSTER32** [comment]
> I have found a workaround with the following steps:
> 
> 1. Install Blitz
> 2. Install Blit App Adblock
> 3. Navigate to C:\users\YourWindowsUsername\AppData\Local\blit-update *
> 4. Run installer.exe
> 
> Then the application seems to run ok. I am not seeing ads.
> 
> 
> _With default windows settings the AppData folder may not be visible. If you hit your windows key then type 'folder settings' and press enter -> view panel on top -> tick 'show hidden folders' option - then AppData folders will be visible._

This worked for me, the app opens normally after restarting and the ads are nowhere to be found!
Thanks @adamski90

**Comment by appkins** [comment]
I fixed this issue in a recent PR for windows #60

**Comment by IamKevio** [comment]
I am still having issues getting blitz-app-adblock to work on my PC. Installing blitz-app-adblock-win.exe, and then opening the Blitz application normally after that is still causing it to crash out every time. I have also tried the workaround orginally posted by  
adamski90. 

-Full close Blitz
-Run the adblock installer
-Then navigate and run the installer.exe file under C:/Users/username/AppData/Local/blitz-updater

Blitz does boot back up without crashing after following those directions, but the ads are still loading up as well.

**Comment by majorcyto** [comment]
Kevio, that's because the pull request has not been merged yet so you do not have the updated version that Appkins is talking about. @lulzsun has to merge his changes first before it would work for you again on PC.

**Comment by lulzsun** [comment]
@majorcyto Kevio is talking about doing the process manually. Which is what the pull request does automatically. I've tried doing the same process and it didn't work on my end. But I'll give it another shot later with the pull request.

**Comment by majorcyto** [comment]
Ah yeah, I see what you mean. My bad. I tried it manually before and it didn't work for me either. Not sure what is different about his set-up.

**Comment by SonicGold** [comment]
> 
> 
> I fixed this issue in a recent PR for windows #60

I also tried building with your changes, but ads still appear however. 
I didn't review what the changes were, but I noticed that the installer runs as part of the process now.

**Comment by appkins** [comment]
Not sure if this helps, but I'm using the version of the Blitz app distributed through winget package manager. After running `winget install blitz` and running the script in my PR, Blitz runs without ads.

**Comment by appkins** [comment]
There are some other factors that could come into play. You probably need to do a clean install of Blitz, because I've noticed that Blitz stages new versions of the app with their own asar file to be patched into the application. This directory should not exist if you do a clean install.

**Comment by appkins** [comment]
So I think we need to identify a new part of the Blitz ecosystem to fully resolve the issue: Blitz Updater.

If you're running this against a Blitz app that has already run, the patcher is most likely in place. The patcher's responsibility is to replace parts of the Blitz app with new files, one of those being the asar archive. The program will either need to patch this archive, or wipe the contents of the update directory. I think both solutions will completely resolve the issue

**Comment by gr3ger** [comment]
There has to be some sort of integrity check done. 
Even if you don't repackage the asar and just change a comment block in a hex editor (without changing file size ofc) it still refuses to launch, so I guess we'll have to find exactly where this happens, and then patch it.

**Comment by gr3ger** [comment]
This is the console output that differs between a modified `app.asar` and the original one.
(The modified one has more log output)

```
[11544:0901/131442.346:INFO:CONSOLE(117)] "Received unhandled main message [object Object]", source:  (117)
[11544:0901/131443.152:INFO:CONSOLE(113)] "APP CORE VERSION 1.15.35", source:  (113)
[11544:0901/131443.990:INFO:CONSOLE(117)] "Received unhandled main message [object Object]", source:  (117)
[11544:0901/131444.587:INFO:CONSOLE(178)] "1.15.35 /app/1.15.35/sw.js?version=1.15.35", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131444.596:INFO:CONSOLE(178)] "ServiceWorker registration successful with scope:  https://blitz.gg/app/1.15.35/", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131444.607:INFO:CONSOLE(178)] "%chenlo gamer
          helllo you WONDERFUL GAMER
   want to work on Blitz?
     go apply for a job with us! color:green;font-size:30px;", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131444.607:INFO:CONSOLE(178)] "%cwe are looking for:
  - a good generalist (js/c++/rust/elixir??) color:red;font-size:20px;", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131444.608:INFO:CONSOLE(178)] "%csay hello to me directly: dali@blitz.gg color:blue;font-size:20px;", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131444.744:INFO:CONSOLE(178)] "Setting ads to banners", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131444.834:INFO:CONSOLE(178)] "Updating app version to 1.15.35", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131444.892:INFO:CONSOLE(178)] "Debug: tcloaded", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
[11544:0901/131445.136:INFO:CONSOLE(113)] "APP CORE VERSION 1.15.35", source:  (113)
[11544:0901/131445.163:INFO:CONSOLE(0)] "Error: unauthorized: unauthenticated", source:  (0)
[11544:0901/131446.523:INFO:CONSOLE(178)] "MANUAL GC", source: https://blitz-desktop.blitz.gg/1.15.35/static/js/main.b9b7a72f.js (178)
```

I will keep investigating

**Comment by kotobuki09** [comment]
> 
> 
> Not sure if this helps, but I'm using the version of the Blitz app distributed through winget package manager. After running `winget install blitz` and running the script in my PR, Blitz runs without ads.

Thank man! And It's still showing ads in my case! Hope to get a better solution

**Comment by gr3ger** [comment]
It might be a EU thing due to GDPR.

**Comment by narcoticcoin** [comment]
> > Interesting. This would mean that somewhere in the application there's an inbuilt kill switch for the ads as well.
> 
> that's because they plan to offer a "premium" service in the future for paid accounts which remove ads 🙄

well as of today they are now offering that premium version

**Comment by emlautarom1** [comment]
> However, there are possible ways to go around this issue. One idea that I've thought about trying is to just inject javascript into the electron renderer. [Here's an example](https://github.com/tintinweb/electron-inject) of someone doing this. If anyone wants to test out something like this, I'd like to know the results, as I am currently no longer motivated to fix this on my own time.

Done, you can check my code here: https://github.com/emlautarom1/blitz_block. Run Blitz with remote debugging and run the adblocker. Works just fine as of today

**Comment by 100Daisy** [comment]
I managed to create nearly 1:1 repack of asar file but blitz still crashes wth E6 error

**Comment by 6ixfalls** [comment]
> There has to be some sort of integrity check done. Even if you don't repackage the asar and just change a comment block in a hex editor (without changing file size ofc) it still refuses to launch, so I guess we'll have to find exactly where this happens, and then patch it.
> 
> EDIT: I tried creating a TTD trace of the main EXE, but when doing that it actually booted without crashing. This makes me think it tried to do some network call before verifying the files, which then timed out (and was apparently fine with it timing out) because TTD is kind of slow. Not sure how helpful that knowledge is, but I guess it's good to know that it most likely gets it's info from the web and it's not a bundled hash value or something inside the application.
> 
> The crash always happens after the second window pops up and it establishes a connection (e.g. after the "retry connection" thing pops up if it's having connectivity issues)
> 
> I guess the easiest thing would be if someone had an earlier version of the `app.asar` package that worked with ad blocking to see what exactly changed. And if nothing changed we can at least rule out that it is happening in the JS application.

Took a quick look at the main process for Blitz (debugger), and it seems to run fine up until blitz_core.node is loaded (in which the process crashes when registering game event handlers). There's either some sort of integrity check in blitz_core, or something in there is crashing it.
